### ISSUE TITLE
Script to pull out data from beancount

### ISSUE THREAD

**Issue by mattmccormick** [aaronj1335/personal-finances-dashboard#1]
Hello,

On your [blog post](https://aaronstacy.com/writings/visualizing-personal-finances/) you mention:

> I run some Python scripts to generate the report that contains last month’s data as well as our historical financial information

Would you be able to include the script that you use or at least an example one to help get started?

Thank you

**Comment by aaronj1335** [comment]
Hi Matt, I have a `Ledger` class whose core is a method that iterates over all the transactions, keeping a `beancount.core.inventory.Inventory` for all accounts along the way. [Here's the file in a gist](https://gist.github.com/aaronj1335/8b33d43b266f898c7f4334b55403732e). It's got some assumptions baked in like USD, and how to handle accounts that have multiple commodities (which isn't recommended anyway).

To generate the dashboard, I've got some scripts (which I won't share here since they get into personal details) that use this class's methods to, i.e. take the difference in the sum of all `Income:` accounts from the beginning to the end of the month to get total monthly income, or take the difference in cost basis for all `Asset:` accounts to get yearly savings (though you may need to adjust this logic if you've made significant withdrawals).

Originally I started with beanquery for these, but that gets slow since it doesn't have all the caching that this `Ledger` class can do. I also end up having special cases (i.e. I want a monthly spending report, but I don't want to include a specific purchase since it's a one-time thing and throws the whole chart off). I handle this with metadata annotations on the transactions, and special handling in my reporting scripts that exclude those from a given chart or whatever, and I just found it easier to maintain in Python than beancount's query language.

**Comment by mattmccormick** [comment]
This is great!  Thanks so much.  I'll use this as a starting point.

I've used bean query as well but haven't made that much use of the API yet so this will help a lot.
